version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://${NONGO_PRICECOMPARE_USERNAME}:${NONGO_PRICECOMPARE_PASSWORD}@mongo:27017/price-compare # Connect to MongoDB container ${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@
      - DISPLAY=:0
    ports:
      - "9222:9222"
      - "3000:3000"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
  mongo:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  frontend:
    build:
      context: ./src/web/my-app
    ports:
      - "3001:3001"
    depends_on:
      - app

volumes:
  mongo-data: