version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/price-compare # Connect to MongoDB container
  mongo:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: